### PR TITLE
Lots of new scripts

### PR DESCRIPTION
**Pull request by aomdahl**
Several updates on scripts and things, as well as some new ones for creating the training data. We have some training datasets you can start to use if you'd like!

### CODE REVIEW

**Comment by jdayton3** [comment]
@aomdahl - Looks like there's a merge conflict with something @gageblack pushed yesterday, and I'm not sure which code should be kept.  Can you guys take a look at that?

**Comment by gageblack** [comment]
The one Ashton pushed today is the most recent. However, I am going to add some lines that will write the data to a file, so I will be pushing a new one in a few hours. So it might better to just wait for a little bit before you commit any

**Comment by jdayton3** [comment]
@gageblack Where are we on this?

**Comment by gageblack** [comment]
@jdayton3 We should be good to go now, the newest one I sent today should resolve it all.

**Comment by jdayton3** [comment]
I'm still seeing conflicts here - could one of you resolve those?

**Comment by gageblack** [comment]
I don't know how to resolve them. The one I pushed up yesterday is the most recent one. I took Ashton's code that he tried pushing up and added output statements. Is it possible to just commit the last request?

**Comment by jdayton3** [comment]
OK, I just kept @gageblack 's latest code!

**Pull request merged**
